Changes, lib/npg/samplesheet.pm
samplesheet generation: library id shoudl be defined for all samples
=> enforce library_id defined

Changes, lib/st/api/base.pm, lib/st/api/batch.pm, lib/st/api/event.pm, lib/st/api/project.pm, lib/st/api/sample.pm, lib/st/api/study.pm, t/40-st-base.t, t/40-st-event.t
Added a method to transparently return live or dev LIMs base URL.
We need it whe reporting manual qc results.
=> method to transparently return live or dev LIMs base URL

Changes, wtsi_local/envvars
Currently the upstream of the live apache web server installation should have www-live dir. This change hardcodes the dev environment. A switch to live env should be done explicitly by setting the value of dev variable to live or removing this variable alltogether similar to how we currently change the dev port to live one with a sed comand.
Eliminating the need for the www-live dir should allow for keeping all apache installation inside the dated directory on gseq.
=> apache: set dev env var explicitly

lib/npg_tracking/data/bait/find.pm
when building bait_path multiple references now generate a warning message rather than croaking
=> when building bait_path replace croak by a warning message

Build.PL
Declared a dependency missing from ClearPress as a workaround for
https://rt.cpan.org/Public/Bug/Display.html?id=111667
=> Declared a dependency missing from ClearPress

lib/npg_testing/db.pm, t/10-npg_testing-db.t
Enable UTF-8 support in SQLite test databases when the appropriate attribute is set.
Check UTF-8 when reading/writing YAML.
Added an option to silence fixture loading chatter.
=> Enable UTF-8 support in SQLite test databases when it is enabled for MySQL

lib/st/api/lims.pm
"0" had been skipped - now consider values defined and length>0
This get more appropriate values for lane and tag 0 for "qc_state"
=> Consider values of "0" when obtaining multiple attribute values

lib/st/api/lims.pm
When creating children recursively, avoid repeatedly implicitly building primary attr on a driver.
For ml_warehouse driver, when the id_run attribute is not given on a flowcell level, it is built once on the run level in _cached_children (I believe) and then reused for descendants. In the current version it is built for each descendant.
=> give priority to known values of primary attributes

Changes, lib/npg_tracking/daemon/samplesheet.pm, t/16-npg_tracking-daemon-samplesheet.t
Running the currently deployed code to generate a samplesheet on sf49-nfs gives an error - reference repository is not visible.
I have successfully run this fixed daemon on sf49-nfs against a dev tracking database. Log messages appear in the daemon's log as expected. The samplesheet is generated.
=> samplesheet daemon: fixed logger; changed reference repository root

Build.PL, Changes, MANIFEST, lib/npg_tracking/glossary/composition.pm, lib/npg_tracking/glossary/composition/factory.pm, lib/npg_tracking/glossary/composition/factory/attributes.pm, lib/npg_tracking/glossary/composition/factory/rpt.pm, lib/npg_tracking/glossary/composition/serializable.pm, t/10-npg_tracking-glossary-composition-factory-attributes.t, t/10-npg_tracking-glossary-composition-factory.t, t/10-npg_tracking-glossary-composition.t
…e (as much as
it is practically possible in Perl):
- functionality for an incremental assembly of a composition moved to
a generic composition factory;
- empty compositions are not allowed;
- sort is performed by the constructor and removed from other functions;
- integrity check when serializing composition;
- Composition - find uses binary search.
- Required version of List::MoreUtils increased to make binary search available.
=> immutable composition

.travis.yml
Recent release of mysql (5.7.14) breaks our builds. Until version can be fixed to 5.7.13 use default travis mysql to keep CI working
=> introduce regresion to default mysql until fix

Build.PL, Changes
Install all files, including files for the web app, in one go withing the "install" action.
To avoid excessive verbal output, use Module::Build methods to find and copy files.
=> drop separate webinstall

lib/st/api/lims.pm, lib/st/api/lims/samplesheet.pm, t/40-st-lims.t
These changes permit the samplesheet driver to find its samplesheet file path correctly from `NPG_CACHED_SAMPLESHEET_FILE` when necessary.
I moved the automatic setting of the path attribute from within the `st::api::lims::driver_type` builder  to its own builder method in `st::api::lims::samplesheet`.
I altered the tests to reflect that the `driver_type => 'samplesheet'` initarg alone may be used to set the driver type of `st::api::lims`, the samplesheet file `path` initarg no longer being required to pass to the driver's constructor.
=> Allow the samplesheet path to be determined by the environment

Changes, lib/npg_tracking/data/reference/find.pm, lib/npg_tracking/data/transcriptome.pm, lib/npg_tracking/data/transcriptome/find.pm, t/10-reference-find.t, t/10-transcriptome.t
Return aligner when parsing reference genome string
- This is a completely different approach from previous commit but the aim is the same: parse the _analysis_ name expected to be at the end of the reference genome string, between '[]', and even if there is no transcriptome version present (so not only for RNA-Seq)
- Change is compatible with current usage of the find() method in reference module
- Test module was changed to add new parsing scenarios
- Update the changelog accordingly
=> pick analysis using ref genome string

lib/npg_tracking/data/transcriptome/find.pm, t/10-transcriptome.t
This method is used by the RNA-SeQC check which uses the file to estimate the globin genes contents in a bam file
=> Add method to find file with globin genes inside transcriptome repo

Changes, data/templates/instrument_read.tt2, data/templates/run_list.tt2, lib/npg/model/instrument.pm, t/10-model-instrument.t, t/20-view-instrument.t, t/data/rendered/instrument/11.html, t/data/rendered/run/runs_on_instrument.html
... and fix run listing for an instrument.
Customer complained about slow loading of the instrumemt page due to a large numebr of instrument statuses being rendered, especially for a MiSeq instrument.
Customer tested on dev server, reported considerable imprvement.
=> limit num instrument statuses displayed

Changes, lib/npg_tracking/glossary/moniker.pm, t/10-npg_tracking-glossary-moniker.t
npg_pipeline::product has some functionality that is generic enough to be included into the moniker role. This pr moves extends the moniker role with the functionality of the file_name method of the product class. Error conditions are treated in a more user-friendly way.
=> extended functionality for the moniker role

lib/npg_tracking/glossary/moniker.pm, t/10-npg_tracking-glossary-moniker.t
Seems to be a bug in MooseX::Getopt which makes its introspection of a private attribute with 'init_arg'  set to {} to go wrong. As a consequence, two entries like ''HASH(0x71b9480)!',' appears in the option spec that is passed to Getopt::Long. This spec is then rejected with an error
Error in option spec: "HASH(0x71b9480)!"
Error in option spec: "HASH(0x71b9480)!"
=> ensure the moniker role is compatible with MooseX::Getopt

Changes, lib/npg_tracking/glossary/composition/component/illumina.pm, t/10-npg_tracking-glossary-composition-component-illumina.t
I doubt it was ever used. Now the moniker role should be used to generate file names
=> filename method of the illumina component removed

t/10-npg_tracking-glossary-composition-component-illumina.t, t/10-npg_tracking-glossary-composition.t
If the clone is not tagged (as it happens in Travis CI) and the git tag does not start with a number, we add 0.0- to the module version when building the package, see https://github.com/wtsi-npg/perl-dnap-utilities/blob/5c3fe8575c4da2fe712d6e3022623cfe10618149/lib/WTSI/DNAP/Utilities/Build.pm#L94
=> flexible comparison that allows for the clone not to be tagged

Build.PL, Changes, bin/npg_status2file, lib/npg_tracking/monitor/status.pm, t/36-npg_tracking-monitor-status.t
With this fix the behaviour of the monitor becomes consistent regardless of whether inotify is enabled.
Also ensure no two statuses of the same run/lane have the same timestamp so that the iscurrent db flag could be assigned inambigiously.
=> use mtime to recognise when a status file has changed

Build.PL
00-scripts_compile.t failing with Test::Compile version 2 in travis.
=> restrict test_requires version of Test::Compile to < 1.4

Changes, lib/npg_tracking/illumina/run/long_info.pm, t/60-illumina-run-long_info.t
This determines the optical distance used when marking duplicates.
=> add uses_patterned_flowcell attribute to long_info. 

lib/npg_tracking/illumina/run/folder.pm, t/60-illumina-run-folder.t
This directory holds data that persists between functions but that we don't want to archive to IRODS.
=> Add no_archive folder to npg_tracking::ilumina::run::folder

.travis/before_install_mysql57.sh
URLs we used to use are not valid any longer.
Also, upgrade to packages for bionic.
=> TravisCI MySQL serve build: update URL

Changes, lib/npg_tracking/util/pipeline_config.pm, t/10-npg_tracking-util-pipeline_config.t
a hash containing the config was previously exposed - not useful for pipeline scripts
=> expose product config path

Changes, MANIFEST, lib/npg_tracking/util/pipeline_config.pm, t/10-npg_tracking-util-pipeline_config.t, t/data/pipeline_config/study_config_tertiary_present/product_release.yml
Assumes tertiary analysis will only be set at the study, and not global, level for some time.
=> minor change to npg_tracking::util::pipeline_config

Changes, data/templates/instrument_format_list.tt2, data/templates/instrument_top.tt2, lib/npg/model/instrument_format.pm, t/10-model-instrument_format.t
- Remove non-current instrument formats and `Is Current` column
- Change `Instrument Count` column to `Current Instrument Count`
- Rename link in header from `formats` to `current formats`
Closes #595
=> Change instrument formats page to show only current formats

Changes, MANIFEST, bin/npg_status2file, bin/npg_status_save, lib/npg_tracking/status.pm, t/10-npg_tracking-status.t, t/70-bin-npg_status2file.t
The status monitor is going to be decomissioned in favour of saving
statuses to the database by pipeline jobs. We'd like to maintain an
ability to cteate JSON files with statuses, so the npg_status2file script
is extended to optionally save the status to a database.
When the pipeline is changed to use the new `--db_save` option, we might need to temporarily comment out JSON file creation so that the status daemon, which will have to run for some time after the change is introduced is not creating  superfluous database entries.
=> Optionally save run and lane statuses to the database.

Changes, t/util.pm
NPG_TEST_TRACKING_CONFIGPATH environment variable can be used to set
a custom location of the Clearpress configuration file for unit tests.
If this variable is unset, a default location of the configuration
is used.
This functionality will be used when running a full stack tests when we do not have a direct access to tracking conf file for tests. Password-less MySQL access for a root is not encouraged these days.
=> Custom location of the Clearpress configuration file for unit tests.

Changes, wtsi_local/httpd_sfweb.conf
As suggested by dj3 it would be best to compile a whitelist but in the meantime block tsv files (artic pp pipeline variant files).
=> Block access to tsv files via httpd_sfweb.conf

Changes, lib/st/api/lims.pm, t/40-st-lims-mlwarehouse.t
Create 'primer_panel' alias for the 'gbs_plex_name' method in
st::api::lims. The new accessor will be used in contexts that are
outside of processing GBS runs. Thi scommit partially resolves
https://github.com/wtsi-npg/npg_tracking/issues/632
=> Create 'primer_panel' alias for 'gbs_plex_name'.

Build.PL, Changes, lib/npg/view.pm
After moving npg_tracking to containers in head nodes and once staging areas
are not local to head nodes, the check is not valid anymore. We expect staging
areas will be independent of farm head nodes (different filesystem) and we are
not allowing the container to access local filesystems where staging areas
would be.
=> remove collocation checks for staging area links

Changes, wtsi_local/httpd_sfweb.conf
Removed ability of the tracking server to provide directory
views of visible to the server /nfs partitions since nfs
staging servers are no longer used.
=> Restrict web server directory views to /export

.github/workflows/testing_and_building_repos.yml
Run `apt-get update` to ensure apt doesn't fetch a nonexistent package. Also add `libgd-text-perl` which isn't included in `libgd-dev` anymore.
=> Fix broken libGD package in CI

bin/staging_area_monitor, lib/Monitor/Staging.pm, t/34-monitor-staging.t
Depends on https://github.com/wtsi-npg/npg_tracking/pull/716
Bring the code in accordance with the current practice:
- consider only one staging area,
- narrow down the glob pattern for areas below the staging
area to 'IL*'.
=> Further simplification of the staging daemon

bin/staging_area_monitor, lib/Monitor/RunFolder/Staging.pm, t/34-monitor-runfolder-staging.t
Removed exessive complexity in finding RTACpmplete.txt and CopyComplete.txt files.
Removed a second round of examining the above files at the stage of deciding whether the mirroring has been completed.
Removed examination of the content of the Error log file since it is not present in the runfolders created by the contemporary instruments.
=> Simplified run complete and mirrored detection.

bin/staging_area_monitor, lib/Monitor/RunFolder/Staging.pm, t/34-monitor-runfolder-staging.t
Previously we were looking at the wrong file in the wrong place. Now we are waiting for the output of the onboard analysis to be copied to staging. This is a step towards declaring the run as mirrored.
=> Reimplemented waiting for the onboard analysis.

Changes, bin/npg_move_runfolder
MooseX::Getopt is no longer used by the underlying class, therefore the arguments have to be processed explicitly. With this change a better control of
input arguments is achieved.
Documentation is updated and extended.
=> Fixed a regression in npg_move_runfolder.

cgi-bin/locate_runfolder
Cope with `{a,b}*` in glob.
Some vestigial functionality is removed.
Present page with options when there are multiple results from ~the~ [any] glob.
=> locate_runfolder: simplify, cope with complex globs, link page for multiple locations

Changes, lib/npg/samplesheet.pm, t/47-samplesheet.t
Switched the default LIMS driver in samplesheet generation from 'xml' to 'ml_warehouse'.
Added 'lims_driver_type' attribute to npg::samplesheet. Updated the tests for samplesheet generation, which are using the xml LIMS driver, to set the driver type explicitly.
=> Switched default LIMS driver in samplesheet generation

t/40-st-lims-samplesheet.t, t/40-st-lims.t
Some tests use lims objects that are created with the xml lims driver for comparison. This was useful at a time when new driver types were introduced. No longer of value.
=> Drop tests that use xml lims driver.

lib/npg/samplesheet/auto.pm
Recently, the default LIMS driver type in samplesheet generation was changed to 'ml_warehouse'. Following this change, the code for auto-generation of MiSeq default samplesheets is now simplified to exclude
an explicit creation of LIMS objects.
=> Simplified samplesheet auto-generation code.

lib/npg_tracking/illumina/run/long_info.pm, t/60-illumina-run-long_info.t
In practice we never automatically merged rapid runs, this flag was reverted to false for them by the pipeline. Instruments on which rapid runs were performed are no longer in use.
=> Restricted automatically meargeable to NovaSeq.

Changes, wtsi_local/httpd.conf
Pull out specific config change bits from the other [PR](https://github.com/wtsi-npg/npg_tracking/pull/764) to create a bugfix release.
=> Single change event cfg so we can bugfix release

MANIFEST, lib/npg_tracking/illumina/run/long_info.pm, t/60-illumina-run-long_info.t, t/data/run_params/RunParameters.novaseqx.prod.xml
We use the name of the Application in RunParameters.xml to detect that the instrument belongs to the NovaSeq type. Newer NovaSeqX instrument we have has the following definition for the application:
<Application>NovaSeqXSeries Control Software</Application>
This pull request fixes the reg exp we use to ensure that the above definition does not result in the instrument being classified as NovaSeq.
=> Distinguish between NovaSeq and NovaSeqX RunParams.

lib/npg/samplesheet.pm, t/47-samplesheet.t
XML driver for st::api::lims was removed some time ago...
The build method the 'lims' attribute is simplified since only the ml_warehouse driver is now used.
Removed the lims_driver_type attribute, which was introduced in order to set the driver type to 'xml' to keep the tests, which used that driver, alive.
=> Removed provisions for XML driver in samplesheet generation.

bin/npg_samplesheet_generator_NovaSeqXSeries, lib/npg/samplesheet/novaseq_xseries.pm, t/47-npg_samplesheet_novaseq_xseries.t
Commented out code deleted.
Attributes and methods are ordered more logically. Some private accesors are converted to public.
Documentation improved.
Added index_read_length and read_length attributes so that these values can be set by the caller.
=> Improved samplesheet generation for NovaSeqX.

MANIFEST, lib/npg/samplesheet.pm, lib/npg/samplesheet/base.pm, lib/npg/samplesheet/novaseq_xseries.pm, t/.npg/npg_tracking, t/47-npg_samplesheet_novaseq_xseries.t, t/47-samplesheet.t
Built on top of https://github.com/wtsi-npg/npg_tracking/pull/794
Created a parent class for two existing samplesheet
generators. Moved common methods to this class.
Through this inheritance the NovaSeqX samplesheet
generator gets a standard method for setting a path for the
samplesheet.
An option to set the path from a value in the configuration file
is dropped - it was not used for years.
=> Ability to set a path for NovaSeqX samplesheet

lib/st/api/lims.pm, t/40-st-lims-merge.t, t/40-st-lims-mlwarehouse.t, t/40-st-lims.t
This pr is resolves a bug that went untetected for a long time. The bug came to light while refactoring the samplesheet generation for NovaSeqX. The samplesheet daemon uses the `ml_warehouse` driver. A silent switch to the default samplesheet driver was happenning, which resulted in an error since the samplesheet to read from cannot be found. While extending the tests in this pr, another variation of this bug was observed - a switch from a connection to the test database to a connection to a live database.
=> Correctly propagate driver details for mlwh driver

lib/st/api/lims.pm, t/40-st-lims.t
Was needed when we used the xml driver.
No current lims driver is using this argument. Existing production code does not pass batch_id to st::api::lims constructor.
st::api::lims documentation updated.
=> Removed st::api::lims batch_id constructor arg.

MANIFEST, bin/npg_samplesheet4NovaSeqX, bin/npg_samplesheet_generator_NovaSeqXSeries, lib/npg/samplesheet.pm, lib/npg/samplesheet/auto.pm, lib/npg/samplesheet/base.pm, lib/npg/samplesheet/novaseq_xseries.pm, t/47-npg_samplesheet_auto.t, t/47-npg_samplesheet_novaseq_xseries.t
Built on top of https://github.com/wtsi-npg/npg_tracking/pull/795
=> Daemon4novaseqx samplesheet

Changes, data/npg_tracking_email/templates/run_status2followers.tt2, data/npg_tracking_email/templates/urls.tt2, data/npg_tracking_email/templates/wrapper.tt2, t/80-npg_tracking-report-event2subscribers.t, t/data/report/report_text_1, t/data/report/report_text_5
Signature change as well as updating the iRODS help page link.
Remove (temp) the link to runs/illumina qc page.
=> Update emails for status change

bin/staging_area_monitor, lib/Monitor/RunFolder.pm, lib/Monitor/RunFolder/Staging.pm
Added runfolder path to some of log messages so that it is easier to search the logs.
Added comments to the staging monitor scripts to highlight that the script is likely to discover and process shadow runfolders.
=> Added logging to help monitor shadow run folderes.

lib/st/api/lims.pm, t/40-st-lims-merge.t
A more generic aggregate_libraries method can be used instead.
Depends on https://github.com/wtsi-npg/npg_seq_pipeline/pull/815
=> Deleted aggregate_xlanes method from st::api::lims

Build.PL, Changes, MANIFEST, lib/npg_tracking/illumina/run/folder.pm, lib/npg_tracking/illumina/run/short_info.pm, lib/npg_tracking/illumina/runfolder.pm, t/60-illumina-run-folder.t, t/60-illumina-run-long_info.t, t/60-illumina-run-short_info.t, t/60-illumina-runfolder.t
This is a breaking change for lots of old-fashion tests. All NPG Perl git reposhave been tested against this change. The following tests are failing in npg_seq_pipeline:
- t/10-pluggable.t                            
- t/20-function-current_analysis_link.t        
- t/20-function-seq_alignment.t                  
- t/20-function-warehouse_archiver.t             
The rest of repos are fine
=> Stop parsing run info from run folder name

data/templates/instrument_list_textual.tt2, lib/npg/model/instrument.pm, t/10-model-instrument.t, t/data/fixtures/300-run.yml
Added a column for recently used staging servers so that the loaders can easily spot instruments, which write to the same server.
=> Enhanced a textual listing of instruments.

Changes, MANIFEST, lib/npg_tracking/data/reference/find.pm, lib/npg_tracking/data/reference/util.pm, lib/st/api/lims.pm, t/10-reference-find.t, t/10-reference-util.t
Moved the parser for the LIMS reference genome notation from npg_tracking::data::reference::find to a new package npg_tracking::data::reference::util, thus providing a stand-alone implementation of the parser.
Removed dependency of st::api::lims on npg_tracking::data::reference::find since the latter brings in dependency on npg_tracking::data::reference::list, which requires that the reference repository root is defined and exists.
=> Created a stand alone ref. genome name parser.
