t/45-st-api-lims-traversal.t
mlwarehouse lims driver live test fix following reloading data to the wh database and fixes in the DBIx binding for the driver
=> mlwarehouse lims driver live test fix

t/36-npg_tracking-monitor-status.t
=> mark failing test as TODO

Changes, lib/Monitor/Cbot.pm, lib/Monitor/Cbot/InstrumentStatus.pm, lib/Monitor/Cbot/RunInfo.pm, lib/Monitor/Cbot/RunList.pm, lib/Monitor/Instrument.pm, lib/Monitor/Roles/Cycle.pm, lib/Monitor/Roles/Schema.pm, lib/Monitor/Roles/Username.pm, lib/Monitor/RunFolder.pm, lib/Monitor/RunFolder/Staging.pm, lib/Monitor/SRS.pm, lib/Monitor/SRS/FTP.pm, lib/Monitor/SRS/File.pm, lib/Monitor/SRS/Local.pm, lib/Monitor/Staging.pm
if no batch_id or it is 13 digits long
=> No longer block move from run mirrored to analysis pending

Changes, MANIFEST, lib/npg/samplesheet.pm, lib/npg_tracking/daemon.pm, lib/npg_tracking/data/reference/find.pm, lib/npg_tracking/data/reference/list.pm, lib/npg_tracking/data/snv/find.pm, lib/npg_tracking/data/transcriptome/find.pm, lib/npg_tracking/illumina/run/folder.pm, lib/npg_tracking/util/abs_path.pm
to cope with running code on a file server where the abs_path may
differ from the cannonical network path
=> use custom abs_path which adds substitution mechanism

Changes, lib/st/api/lims.pm, t/40-st-lims.t
find driver_type from driver if provided
=> minor lims shim enhancement

lib/npg/samplesheet.pm, lib/st/api/lims/samplesheet.pm
works with wtsi-npg/npg_seq_pipeline#150
=> Cope with UTF8 lims info

Build.PL, lib/st/api/lims.pm, lib/st/api/lims/samplesheet.pm
prior to moving to lims for compositions.
=> lims code tidy-up

Changes, lib/npg_tracking/glossary/composition/factory/attributes.pm, lib/npg_tracking/glossary/composition/factory/rpt.pm, t/10-npg_tracking-glossary-composition-factory-attributes.t, t/10-npg_tracking-glossary-composition-factory-rpt.t
Tested with npg_qc and npg_seq_melt. One insignificant test fails in npg_qc, will fix with a separate pull request if these changes are released without further changes to npg_qc.
=> improvements for composition factories

Changes, data/templates/actions.tt2, data/templates/run_read.tt2, t/data/rendered/actions_admin.html, t/data/rendered/actions_analyst.html, t/data/rendered/actions_annotator.html, t/data/rendered/actions_engineer.html, t/data/rendered/actions_loader.html, t/data/rendered/actions_public.html
... since the pages moved to SeqQC
Depends on https://github.com/wtsi-npg/npg_qc/pull/365
=> updated links to NPG QC

.travis.yml, .travis/before_install.sh
To bring this build in line with Travis CI builds for other NPG packages
=> Travis CI build - do not hardcode NPG Perl dependencies version

t/16-npg_tracking-daemon-jenkins.t, t/16-npg_tracking-daemon-samplesheet.t
=> tests fixes for gseq cluster

Changes, lib/npg_tracking/report/events.pm
New order
2017/05/11 19:51:19 INFO  npg_tracking.report.event2lims - DRY RUN Run 22388 : qc review pending
2017/05/11 19:51:19 INFO  npg_tracking.report.event2lims - DRY RUN Run 22388 : qc review pending
2017/05/11 19:51:19 INFO  npg_tracking.report.event2lims - DRY RUN Run 22388 : qc review pending
2017/05/11 19:51:19 INFO  npg_tracking.report.event2lims - DRY RUN Run 22388 : qc review pending
2017/05/11 19:51:19 INFO  npg_tracking.report.event2lims - DRY RUN Run 22388 : qc review pending
2017/05/11 19:51:19 INFO  npg_tracking.report.event2lims - DRY RUN Run 22388 : qc review pending
2017/05/11 19:51:19 INFO  npg_tracking.report.event2lims - DRY RUN Run 22388 : qc review pending
2017/05/11 19:51:19 INFO  npg_tracking.report.event2lims - DRY RUN Run 22388 : qc review pending
2017/05/11 …
=> notification order change

.travis.yml, Changes
https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
=> set explicit dist in travis yml

Changes, MANIFEST, lib/npg_tracking/glossary/composition/factory/rpt_list.pm, t/10-npg_tracking-glossary-composition-factory-rpt_list.t
=> factory class for rpt_list->composition transformation

Changes, lib/npg_tracking/glossary/rpt.pm, t/10-npg_tracking-glossary-rpt.t
Tested npg_qc, npg_seq_melt, npg_seq_pipeline, npg_ml_warehouse against this change. Two tests in npg_qc will have to be adjusted (error message for an invalid rtp key has changed).
=> Typed rptkey inflation

data/templates/instrument_read.tt2, t/data/rendered/instrument/11.html
=> remove uptime info from instrument page

Changes, data/templates/actions.tt2, data/templates/administration_list.tt2, data/templates/instrument_list_graphical.tt2, data/templates/instrument_read.tt2, data/templates/instrument_status_add.tt2, data/templates/instrument_status_annotation.tt2, data/templates/run_add.tt2, data/templates/search_list_advanced.tt2, t/data/rendered/20-view-administration_list_admin.html, t/data/rendered/20-view-administration_list_engineers.html, t/data/rendered/20-view-administration_list_public.html, t/data/rendered/20-view-run-form_for_batch_updates_on_list_when_loader.html, t/data/rendered/actions_admin.html, t/data/rendered/actions_analyst.html, t/data/rendered/actions_annotator.html, t/data/rendered/actions_engineer.html, t/data/rendered/actions_loader.html, t/data/rendered/actions_public.html, t/data/st_api_lims_new/npg/designation/3.xml, wtsi_local/httpd_sfweb.conf
Another server-related pr follows soon, no need to test/review this one in isolation
=> remove unnecessary aliasing of urls

Changes, lib/npg_tracking/illumina/run/long_info.pm, t/34-monitor-runfolder.t, t/60-illumina-run-long_info.t, t/60-illumina-runfolder.t
Remove unused methods and attributes, update documentation, format the code.
This is a clean base for further changes to long_info.
=> long_info role tidy-up

lib/npg_tracking/data/reference/find.pm, t/10-reference-find.t, t/10-reference.t, t/90-reference.t
Designed to force explicit aligner declaration e.g. `bwa0_6` in other code
=> Reference lookup to default to fasta

Changes, lib/npg_tracking/data/transcriptome/find.pm, t/10-transcriptome.t
- Lists of genes in csv format need to be in place otherwise send and error, like all the other _find_ methods
Depended on by: https://github.com/wtsi-npg/npg_qc/pull/539
=> Implement find list of MT genes in transcriptome repository

wtsi_local/httpd.conf
make the configuration compatible for farm and esa deployments
=> update httpd.conf for esa

t/36-npg_tracking-monitor-status.t
to detect that the test is running under Jenkins and to skip
tests that start and stop status daemon
=> skip a few tests when running under Jenkins

Changes, bin/staging_area_monitor, lib/Monitor/RunFolder.pm, lib/npg_tracking/Schema/Result/Run.pm, lib/npg_tracking/Schema/Result/Tag.pm, scripts/upgrade_schema/upgrade_schema-87.4, scripts/upgrade_schema/upgrade_schema-88.0, t/14-dbic-Run.t, t/14-dbic-Tag.t, t/data/dbic_fixtures/000-Tag.yml, t/data/fixtures/000-tag.yml
Built on the top of https://github.com/wtsi-npg/npg_tracking/pull/493
=> simplification of tag handling in DBIx classes

Changes, bin/staging_area_monitor, lib/Monitor/RunFolder.pm, lib/npg_tracking/Schema/Result/Run.pm, lib/npg_tracking/illumina/run/folder/validation.pm, lib/npg_tracking/illumina/run/long_info.pm, scripts/upgrade_schema/upgrade_schema-87.4, t/14-dbic-Run.t, t/34-monitor-instrument.t, t/34-monitor-runfolder.t, t/60-illumina-run-long_info.t, t/data/dbic_fixtures/100-InstrumentFormat.yml, t/data/dbic_fixtures/200-Instrument.yml, t/data/dbic_fixtures/300-Run.yml
Built on the top of https://github.com/wtsi-npg/npg_tracking/pull/494
Part of bin/staging_area_monitor code re-flowed to make it more readable
=> staging monitor to set the instrument side and workflow type tags

Build.PL, Changes, lib/npg_tracking/monitor/status.pm, lib/npg_tracking/status.pm, t/10-npg_tracking-status.t
in WTSI::DNAP::Utilities::Timestamp
Depends on https://github.com/wtsi-npg/perl-dnap-utilities/pull/30
=> status monitor to use timestamp functions defined elsewhere

.travis.yml
=> Travis CI build on Ubuntu Bionic with Perl 5.26.0

Changes, bin/staging_area_monitor
To be tested against dev database
=> flowcell barcode validation

Changes, lib/st/api/lims.pm, t/40-st-lims.t
=> method to create a lane-level st::api::lims object

Changes, lib/Monitor/RunFolder/Staging.pm, t/34-monitor-runfolder-staging.t
We should rename all the npg_do_not_move to npg_do_not_delete before this is released.
=>  discontinue 'npgdonotmove' and 'npg_do_not_move' flags

Changes, MANIFEST, data/templates/administration_create_instrument_status.tt2, data/templates/administration_create_run_status.tt2, data/templates/administration_list.tt2, lib/npg/view/administration.pm, t/20-view-administration.t, t/data/rendered/20-view-administration_create_instrument_status.html, t/data/rendered/20-view-administration_create_run_status.html, t/data/rendered/20-view-administration_list_admin.html, t/data/rendered/20-view-administration_list_engineers.html
Remove 'New Instrument Status' and 'New Run Status' options from the admin page
=> Remove admin status options

scripts/change_user_roles.pl
Is this what you had in mind @mgcam ? Or do you need even more admin capabilities?
=> Create a script to make it easier to add groups for users

scripts/change_user_roles.pl
Accidentally let formatting contaminate a the list of role names.
=> Bugfix for change_user_roles.pl creating duplicate role assignemnts

data/templates/run_list.tt2
=> Add folder name to run listing pages.

data/templates/instrument_read.tt2
=> Add external_name to instrument info page.

lib/npg/model/instrument.pm
=> Remove documentation for functions no longer present in the instrument model

Changes, lib/npg_tracking/Schema/Result/Instrument.pm, t/14-dbic-Instrument.t
As requested in [RT737813](https://rt.sanger.ac.uk/Ticket/Display.html?id=737813).
=> Make NovaSeq instruments skip `wash required` status

Changes, data/templates/run_add.tt2, lib/npg/model/run.pm, t/10-model-run.t, t/20-view-instrument.t, t/data/rendered/run.html;add
Remove options 'B', 'C' and 'joint'.
=> Remove old team names from 'add run' dropdown

Changes, singularity/README.md, singularity/apache2-npg_tracking.def
The file needs to be used to override defaults from application.
=> Add npg_tracking configuration link for singularity container

lib/npg/view.pm, scripts/upgrade_schema/update_data-XX.X, t/10-model-instrument_format.t, t/data/dbic_fixtures/100-InstrumentFormat.yml, t/data/fixtures/100-instrument_format.yml
Update test data check ensure that the tested do not fail in presence of new formats.
Dev database data updated
Set up a dev server, make sure the UI looks OK - DONE
=> Add a new instrument format record for NovaSeqX.

Changes, bin/staging_area_monitor
Staging area daemon script: platform_is_NovaSeqX() -> platform_NovaSeqX()
=>  Fixed a bug, an incorrect method name.

MANIFEST, lib/Monitor/RunFolder/Staging.pm, lib/npg_tracking/illumina/run/long_info.pm, t/34-monitor-runfolder-staging.t, t/60-illumina-run-long_info.t, t/data/run_params/RunParameters.novaseqx.onboard.xml
The flag is implemented in the long_info role, which makes it available to any class that inherits from this role, i.e. to most of the code that deals with the run folders.
The implementation examines the content of RunParameters.xml
The new flag replaces the previous implementation of a similar flag in the staging monitor.
=> Flagged planned onboard analysis.

lib/npg/samplesheet/novaseq_xseries.pm, lib/npg_tracking/illumina/run/short_info.pm, t/47-npg_samplesheet_novaseq_xseries.t, t/60-illumina-run-short_info.t, t/data/dbic_fixtures/300-Run.yml
=> Allow NovaSeqX samplesheets to embed instrument and slot

lib/npg_tracking/illumina/run/folder.pm, t/60-illumina-runfolder.t
Allow to find a runfolder in 'analysis' or 'outgoing' in the presence of a duplicate runfolder in 'incoming'.
The duplicates in 'incoming' are sometimes created by instruments well after the run was mirrored and the runfolder moved to 'analysis'.
=> Ability to disregard duplicate runfolders.

lib/npg_tracking/Schema/Result/Annotation.pm, lib/npg_tracking/Schema/Result/Event.pm, lib/npg_tracking/Schema/Result/EventType.pm, lib/npg_tracking/Schema/Result/Instrument.pm, lib/npg_tracking/Schema/Result/InstrumentAnnotation.pm, lib/npg_tracking/Schema/Result/InstrumentDesignation.pm, lib/npg_tracking/Schema/Result/InstrumentFormat.pm, lib/npg_tracking/Schema/Result/InstrumentMod.pm, lib/npg_tracking/Schema/Result/InstrumentStatus.pm, lib/npg_tracking/Schema/Result/InstrumentStatusAnnotation.pm, lib/npg_tracking/Schema/Result/InstrumentUtilisation.pm, lib/npg_tracking/Schema/Result/Run.pm, lib/npg_tracking/Schema/Result/RunAnnotation.pm, lib/npg_tracking/Schema/Result/RunLane.pm, lib/npg_tracking/Schema/Result/RunLaneAnnotation.pm, lib/npg_tracking/Schema/Result/RunLaneStatus.pm, lib/npg_tracking/Schema/Result/RunStatus.pm, lib/npg_tracking/Schema/Result/StCache.pm, lib/npg_tracking/Schema/Result/TagFrequency.pm, lib/npg_tracking/Schema/Result/TagRun.pm, lib/npg_tracking/Schema/Result/TagRunLane.pm, lib/npg_tracking/Schema/Result/User2usergroup.pm
Changes are due to the MySQL database server upgrade to v8.+
=> Updated DBIx classes from the prod database.

.github/workflows/run-tests.yml, Changes, scripts/install_wsi_dependencies.sh
Name variables consistently.
Source dependencies from the branch that is the target.
=> Correct propagation of the CI target branch.

bin/npg_samplesheet4MiSeq, lib/npg/samplesheet/auto.pm, t/47-npg_samplesheet_auto.t
This generator was writted for MiSeq instrument format. Will have to be extended to include NovaSeqX format. This pull request, while not changing the current functionality, opens a way to extend the generator to other formats.
=> Generalised auto-generator for samplesheets.

data/templates/run_read.tt2, htdocs/css/npg.css
=> Added a footer to the tracking run  web page.

.gitlab-ci.yml, Changes, docs/api_usage.md, docs/includes/repo-metadata.md, docs/instruments.md, docs/run_states.md, docs/user_management.md
Addition of CI/CD job to automatically update confluence page for 'docs/instruments.md'
=> Automatic Confluence Update

README.md, docs/tag_semantics.md
... so that that file can be copied to Confluence.
Also deleted a description of the variable that is no longer used.
=> Factored out a section on tags into a file

lib/st/api/lims.pm, t/40-st-lims.t
Added is_lane and composition_object methods to st::api::lims
=> Added is_lane and composition_object methods.

Changes, data/templates/instrument_format_list.tt2, data/templates/instrument_formats_menu.tt2, data/templates/instrument_list_graphical.tt2, data/templates/instrument_list_textual.tt2, data/templates/instrument_status_menu.tt2, data/templates/instrument_top.tt2, data/templates/run_list.tt2, lib/npg/model/instrument.pm, lib/npg/model/instrument_format.pm, lib/npg/model/run.pm, lib/npg/model/run_status_dict.pm, lib/npg/view/instrument.pm, lib/npg/view/instrument_format.pm, lib/npg/view/run.pm, t/10-model-instrument.t, t/10-model-instrument_format.t, t/10-model-run.t, t/10-model-run_status_dict.t, t/20-view-instrument.t, t/20-view-instrument_menus.t, t/20-view-run.t, t/data/fixtures/200-instrument.yml, t/data/rendered/instrument.html, t/data/rendered/menus/instruments_formats.html, t/data/rendered/menus/instruments_status_graphical.html, t/data/rendered/menus/instruments_status_textual.html, t/data/rendered/run.html, t/data/rendered/run/runs_on_instrument.html
Replaces https://github.com/wtsi-npg/npg_tracking/pull/867 and https://github.com/wtsi-npg/npg_tracking/pull/864
=> Tracking pages view by manufacturer.

Changes, MANIFEST, lib/npg_tracking/daemon/elembiostaging.pm, t/16-npg_tracking-daemon-elembiostaging.t
Built on top of https://github.com/wtsi-npg/npg_tracking/pull/884
=> Elembio tracking daemon
